groups:

  - steps:

      - type:      popup
        text:      { content: welcome }
        options:   [savepoint, hideFooter]
        page:      'index.php?controller=AdminDashboard'

  - title: { loc: group.2.title }

    subtitle:
      1: { loc: group.2.subtitle.1 }
      2: { loc: group.2.subtitle.2 }

    steps:

      - type:     tooltip
        text:     { loc: group.2.step.1 }
        options:  [savepoint]
        page:     ['product/new', 'product/form']
        selector: '#form_step1_name_1'
        position: right

      - type:     tooltip
        text:     { loc: group.2.step.2 }
        page:     'product/form'
        selector: '#tab_step1'
        position: right

      - type:     tooltip
        text:     { loc: group.2.step.3 }
        page:     'product/form'
        selector: '#product-images-dropzone'
        position: right

      - type:     tooltip
        text:     { loc: group.2.step.4 }
        page:     'product/form'
        # Add an ID into the template to select this element more easily
        selector: '.right-column > .row > .col-md-12 > .form-group:nth-child(4) > .row > .col-md-6:first-child > .input-group'
        position: left
        action:
          selector: '#product_form_save_go_to_catalog_btn'
          action:   'click'

      - type:     tooltip
        text:     { loc: group.2.step.5 }
        page:     'product/catalog'
        selector: '#product_catalog_list table tr:last-child td:nth-child(3)'
        position: left

  - title: { loc: group.3.title }

    subtitle:
      1: { loc: group.3.subtitle.1 }
      2: { loc: group.3.subtitle.2 }

    steps:

      - type:     tooltip
        text:     { loc: group.3.step.1 }
        options:  [savepoint]
        page:     '?controller=AdminThemes'
        selector: '#js_theme_form_container .tab-content.panel .btn:first-child'
        position: right

#      - type:     tooltip
#        text:     { loc: group.3.step.2 }
#        page:     '?controller=AdminThemes'
#        selector: '.tab-pane.active .dummyfile'
#        position: right

      - type:     tooltip
        text:     { loc: group.3.step.3 }
        page:     '?controller=AdminThemes'
        selector: '#prestastore-content .addons-theme-one:first-child'
        position: right

  - title: { loc: group.4.title }

    subtitle:
      1: { loc: group.4.subtitle.1 }
      2: { loc: group.4.subtitle.2 }

    steps:

      - type:     tooltip
        text:     { loc: group.4.step.1 }
        options:  [savepoint]
        page:     '?controller=AdminPayment'
        selector: '.modules_list_container_tab:first tr:first-child .text-muted'
        position: right

      - type:     tooltip
        text:     { loc: group.4.step.2 }
        page:     '?controller=AdminPayment'
        selector: '.modules_list_container_tab:eq(1) tr:first-child .btn-success'
        position: left

  - title: { loc: group.5.title }

    subtitle:
      1: { loc: group.5.subtitle.1 }
      2: { loc: group.5.subtitle.2 }

    steps:

      - type:     tooltip
        text:     { loc: group.5.step.1 }
        options:  [savepoint]
        page:     '?controller=AdminCarriers'
        selector: '#table-carrier tr:eq(2) td:eq(3)'
        position: right

      - type:     tooltip
        text:     { loc: group.5.step.2 }
        page:     '?controller=AdminCarriers'
        selector: '.modules_list_container_tab tr:eq(0) .text-muted'
        position: right

  - title: { loc: group.6.title }

    subtitle:
      1: { loc: group.6.subtitle.1 }
      2: { loc: group.6.subtitle.2 }

    steps:

      - type:     tooltip
        text:     { loc: group.6.step.1 }
        options:  [savepoint]
        page:     'module/catalog'
        selector: '.page-head-tabs .tab:eq(0)'
        position: right

      - type:      popup
        text:      { content: end }
        options:   [savepoint, hideFooter]
        page:      'product/catalog'
